### ISSUE TITLE
Prefix installer with Active Solution Platform value

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#116]
Optional prefixing of the installer by either x86, x64 or AnyCPU.

**Comment by shiftkey** [comment]
So I've been thinking on this a bit and I thought I'd run through what happens when you run `New-Release`:
1. Remove old .nupkg files (TODO)
2. Using the specified project configuration (Debug/Release/???), build the project and it's dependencies
3. foreach package created it, transpile it into a release package
4. for the latest package, create an installer

Now, we don't actually care about the project configuration you've chosen (perhaps that's a risk if you're using Debug but mean Release) but the architecture specified is a whole other topic (because you can even mix x86/x64 projects and it appears as "Mixed").

So I guess what I'm coming around to is:
- are we simply renaming the installer here based on the active solution settings?
- are we expecting different installers for different platforms? (which will impact build, packages, installer, etc)

Let me know what your thoughts are on this

**Comment by peters** [comment]
> Now, we don't actually care about the project configuration you've chosen (perhaps that's a risk if you're using Debug but mean Release) but the architecture specified is a whole other topic (because you can even mix x86/x64 projects and it appears as "Mixed").

https://github.com/github/Shimmer/issues/176

[$platformTarget$] is derived from the main assembly 

``` xml
<shimmer>
  <!-- specify main assembly (optional of course) -->
  <mainAssembly>myproject.csproj</mainAssembly>
  <!-- derived from main assembly csproj -->
  <installerPrefix>[$platformTarget$]</installerPrefix>
</shimmer>
<files>
   <!-- copy dependencies from x86/x64/anycpu folder -->
   <file src="..\..\external\something\[$platformTarget$]\dependency.dll" target="lib\net45\[$platformTarget$]" />
</files>
```

You should also be able to specify a configuration to build.

1) New-Release -Configuration ReleaseX64
1) New-Release -Configuration ReleaseX86
1) New-Release -Configuration DebugX64
1) New-Release -Configuration Debug64

Something like this would be absolutly awesome! ;)

**Comment by peters** [comment]
@shiftkey This can be closed.. i'm using https://github.com/peters/myget/blob/master/myget.include.ps1#L1471 instead :)
