### ISSUE TITLE
Missing dependencies during installation

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#133]
https://github.com/github/Shimmer/issues/125#issuecomment-24211506

@shiftkey You got mail.

**Comment by shiftkey** [comment]
So I've pulled out my psychic debugger and walked through that sample you mailed me. 

I think the headaches fall into three buckets:

#### Project references don't seem to be treated differently

The project dependency specified in the csproj file isn't in libs folder of the generated nupkg from VS. I think this is a conscious by the NuGet team because tracing what libraries you need (whether they come from your project or from another NuGet package or from an external library) is probably a hard problem to do automagically.

#### Your `packages.config` content is special

Adding projects in a packages.config are only used externally when the package is created. Perhaps the referenced projects could also create packages (rather easy to setup, see [what we did with Shimmer](https://github.com/github/Shimmer/blob/master/src/CreateReleasePackage/CreateReleasePackage.nuspec#L17) to solve this). 

#### External libraries should be specified in the nuspec file

Referencing assemblies aren't included in the generated NuGet package, so you need to be explicit about that (yep, Shimmer has [had to deal with this too](https://github.com/github/Shimmer/blob/master/src/Shimmer.Core/Shimmer.Core.nuspec#L19))

After I finish the proper sample application, I hope to write up some guidance on how to identify and work through these issues (or at least some quick initial notes).

**Comment by shiftkey** [comment]
I've written a [more formal guide](https://github.com/github/Shimmer/wiki/Specifying-the-right-dependencies) on how to resolve these issues.

Let me know if there's specific things on that list that Shimmer can help do better.

**Comment by peters** [comment]
Excellent explanation! I'll dive in when i get home from work ;)
