### ISSUE TITLE
Excess files in package?

### ISSUE THREAD

**Issue by stefanolson** [Squirrel/OldSquirrelForWindows#220]
When I have built my release using new-release, the .nupkg file contains a ridiculous number of files. As you can see from the picture below it has included versions for .net 2.0, various portable versions et cetera.  The app is 4.5 based, and everything that I need is in the net45 folder, but unfortunately when it installs it is using System.Net.Http.Formatting.dll from portable-wp8+netcore45+net45 rather than net45, so my application doesn't work properly.

So, main question is that I get it to stop including everything except net45?

In the meantime I am using developmentDependency="true" on the packages file so that no packages are included and I am manually including all the DLLs, which appears to be cleaner because of the mess nugget is creating.

![toomanyfiles](https://f.cloud.github.com/assets/1751192/1642606/bddc6c32-588e-11e3-9c16-d26f8adf7d87.png)

**Comment by peters** [comment]
@stefanolson I agree.. that's why i just ditch all the nuget stuff altogether and include all files in the final release directory. This is okay since i already use a custom deploy profile outside of visual studio.

**Comment by anaisbetts** [comment]
So, the problem is, all of those are entirely valid platforms for your .NET 4.5 app - you could very well have a reference to something in one of those folders, if one of the NuGet packages only shipped a Portable variant (or, as many packages do, only shipping a Net20 or Net35 binary). Detecting what binaries you actually use is pretty difficult :-/   I think we could do it, if we SHA1d every binary in the packages directory and compared it to the build output, but that's a Tall Order.

**Comment by stefanolson** [comment]
@paulcbetts The problem with the current situation those that some reason it is picking the wrong DLLs, which caused my application not work, but it's fine, it is easier for me to avoid using the nugget stuff - creates a much cleaner result.
