### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by dchaib** [Squirrel/OldSquirrelForWindows#240]
Is there a way to set the icon for the setup.exe file and Windows program list?

I have looked for one and haven't found any... If there isn't, wouldn't it make sense to use the `iconUrl` from the nuspec file?

**Comment by shiftkey** [comment]
Ok, so there's a couple of icons that could be used here.
- the `iconUrl` in the nuspec
- the resource icon for the `exe` inside the package

But I'm 99% sure we're not using either of these for the setup.exe we generate - because that's coming from our WiX template - [and that's expecting a file on disk](http://wixtoolset.org/documentation/manual/v3/xsd/wix/icon.html)

So as part of creating a release we could specify this - perhaps siphon down the file and cache it somewhere. 

Does that all seem logical?

**Comment by dchaib** [comment]
It does! Let me know if I can help.

**Comment by dchaib** [comment]
I think I can close this! :)
